Repository liquality/sporkwhale-farcaster-frame, pull requests merged in 2024-02, with the labels that each got.

#2 feat: feat/op-dynamic-image
  src/app/frames/[slug]/opengraph-image.tsx
  src/pages/index.tsx
  src/types.ts
  src/utils/generate-frames.ts
  tsconfig.json
Labels: 🔍 Ready for Review, size/M

#3 feat: added leaderboard endpoints for image and html render
  src/app/components/leaderboard.json
  src/app/components/leaderboard.tsx
  src/app/layout.tsx
  src/app/leaderboard/content/page.tsx
  src/app/leaderboard/image/route.tsx
  tsconfig.json
Labels: 🔍 Ready for Review, size/L

#4 Feat/calculate img shown from db
  public/-1_bathingSuit_chain_bracelet_whale.png
  public/-2_chain_bracelet_whale.png
  public/-3_bracelet_whale.png
  public/-4_naked_whale.png
  public/0_glasses_bracelet_chain_bathingSuit_whale.png
  public/1_glasses_bracelet_chain_bathingSuit_laserEyes_whale.png
  public/2_glasses_bracelet_chain_bathingSuit_headSet_whale.png
  public/3_glasses_bracelet_chain_bathingSuit_headSet_diamondHands_whale.png
  public/4_glasses_bracelet_chain_bathingSuit_headSet_diamondHands_crown_whale.png
  public/be_a_follower.png
  public/mint.png
  src/pages/api/post.ts
  src/types.ts
  src/utils/generate-frames.ts
  src/utils/neynar-api.ts
  src/utils/utils.ts
Labels: 🔍 Ready for Review, size/L

#5 Feat/calculate img shown from db
  public/reload.png
  src/create.sql
  src/pages/api/getChannelData.ts
  src/pages/api/post.ts
  src/pages/index.tsx
  src/types.ts
  src/utils/database-operations.ts
  src/utils/generate-frames.ts
  src/utils/image-paths.ts
  src/utils/neynar-api.ts
  src/utils/utils.ts
Labels: size/XL

#6 Feat/channel followers
  src/create.sql
  src/pages/api/insertSeedDataInDb.ts
  src/pages/api/post.ts
  src/utils/database-operations.ts
Labels: 🔍 Ready for Review, size/L

#8 feat: added db indexes for performance
  src/create.sql
Labels: 🔍 Ready for Review, size/M

#9 Feat/refactor flow
  public/expired.png
  src/create.sql
  src/pages/api/getLeaderboardData.ts
  src/pages/api/post.ts
  src/pages/api/updateTraitStatus.ts
  src/pages/index.tsx
  src/types.ts
  src/utils/database-operations.ts
  src/utils/generate-frames.ts
  src/utils/image-paths.ts
  src/utils/question.ts
Labels: 🔍 Ready for Review, size/L

#10 Fix: Resolve bug with setupCollectives api endpoint
  src/pages/api/setupCollectives.ts
  src/utils/constants.ts
  src/utils/contract-operations.ts
Labels: 🔍 Ready for Review, size/S

#11 feat: added update traits cron job config/ settings
  src/app/jobs/update-trait-status/route.ts
  vercel.json
Labels: 🔍 Ready for Review, ✅ Approved, size/S

#13 Feat/error handling
  public/welcome.png
  src/create.sql
  src/pages/api/getChannelData.ts
  src/pages/api/getLeaderboardData.ts
  src/pages/api/insertSeedDataInDb.ts
  src/pages/api/post.ts
  src/pages/index.tsx
  src/types.ts
  src/utils/database-operations.ts
  src/utils/generate-frames.ts
  src/utils/image-paths.ts
  src/utils/question.ts
  src/validate.ts
Labels: 🔍 Ready for Review, size/L

#14 Feat/questions db changes
  src/app/leaderboard/content/page.tsx
  src/app/question-image/route.tsx
  src/create.sql
  src/pages/api/insertSeedDataInDb.ts
  src/pages/api/post.ts
  src/utils/database-operations.ts
  src/utils/farcaster-api.ts
  src/utils/generate-frames.ts
  src/utils/question.ts
Labels: 🔍 Ready for Review, size/L

#15 remove file that caused build error, cleanup logs
  src/app/leaderboard/image/route.tsx
  src/pages/api/getLeaderboardData.ts
  src/pages/api/post.ts
  src/pages/index.tsx
  src/utils/database-operations.ts
  src/utils/farcaster-api.ts
  src/utils/question.ts
  src/validate.ts
Labels: size/M

#18 Feat/clashes
  src/create.sql
  src/pages/api/insertSeedDataInDb.ts
Labels: size/M

#19 add seed data for clashes
  src/create.sql
  src/pages/api/insertSeedDataInDb.ts
Labels: 🔍 Ready for Review, size/L

#20 Feat/leaderboard component
  src/app/components/leaderboard-data.json
  src/app/components/leaderboard-template.tsx
  src/app/leaderboard/content/page.tsx
  src/create.sql
  src/pages/api/getLeaderboardData.ts
  src/pages/index.tsx
  src/utils/getLeaderboardData.ts
Labels: 🔍 Ready for Review, size/XL

#21 Feat/mobile leaderboard
  src/components/expanded-day.tsx
  src/components/icons.tsx
  src/components/leaderboard-mobile.tsx
  src/components/leaderboard.css
  src/pages/index.tsx
  src/types.ts
Labels: 🔍 Ready for Review, size/L

#22 feat: added percentage to clashes
  src/app/jobs/update-clashes/route.ts
  src/utils/getLeaderboardData.ts
  vercel.json
Labels: 🔍 Ready for Review, size/M

#23 feat: updated job for update clashes
  src/app/jobs/update-clashes/route.ts
  src/create.sql
  vercel.json
Labels: 🔍 Ready for Review, size/M

#25 Feat/neynar fix
  src/components/column.tsx
  src/components/leaderboard-desktop.tsx
  src/pages/api/post.ts
  src/utils/neynar-api.ts
  src/utils/parent-urls-mapping.ts
Labels: 🔍 Ready for Review, size/XXL

#26 Chore: Refactor sendReward and recordParicipation api endpoints
  src/pages/api/recordParticipation.ts
  src/pages/api/sendRewards.ts
  src/types.ts
  src/utils/database-operations.ts
  vercel.json
Labels: 🔍 Ready for Review, size/L

#28 Chore: Seed correct channels for production
  src/utils/constants.ts
  src/utils/contract-operations.ts
Labels: 🔍 Ready for Review, size/M

#27 feat: validate user is in channel from airstack
  public/1_correct_response.png
  public/1_incorrect_response.png
  public/1_losing.png
  public/1_question.png
  public/1_welcome.png
  public/1_winning.png
  public/2_correct_response.png
  public/2_incorrect_response.png
  public/2_losing.png
  public/2_question.png
  public/2_welcome.png
  public/2_winning.png
  public/3_correct_response.png
  public/3_incorrect_response.png
  public/3_losing.png
  public/3_question.png
  public/3_welcome.png
  public/3_winning.png
  public/4_correct_response.png
  public/4_incorrect_response.png
  public/4_losing.png
  public/4_question.png
  public/4_welcome.png
  public/4_winning.png
  src/pages/api/post.ts
  src/utils/airstak.ts
  src/utils/graphsql.ts
Labels: 🔍 Ready for Review, size/M

#29 Feat: Implement sporkWhale NFT minting
  src/utils/constants.ts
  src/utils/contract-operations.ts
Labels: 🔍 Ready for Review, size/XL

#30 Feat/update images post endpoint
  public/already_submitted.png
  public/be_a_follower.png
  public/error.png
  public/expired.png
  public/whale_day_1.jpg
  public/whale_day_1.svg
  public/whale_day_2.jpg
  public/whale_day_2.svg
  public/whale_day_3.jpg
  public/whale_day_3.svg
  public/whale_day_4.jpg
  public/whale_day_4.svg
  public/whale_day_5.jpg
  public/whale_day_5.svg
  src/components/leaderboard-desktop.tsx
  src/pages/api/post.ts
  src/seed.sql
  src/utils/database-operations.ts
  src/utils/neynar-api.ts
  src/utils/question.ts
Labels: size/M

#31 fix: added fallback for parent url
  src/utils/neynar-api.ts
Labels: 🔍 Ready for Review, size/S

#32 Feat/debug channel farcasther
  src/components/leaderboard-mobile.tsx
  src/pages/api/post.ts
  src/utils/neynar-api.ts
Labels: 🔍 Ready for Review, size/S

#33 Generate nft metadata
  package.json
  public/metadata/1.json
  public/metadata/2.json
  public/metadata/3.json
  public/metadata/4.json
  public/metadata/5.json
  src/pages/api/generateNftData.ts
  src/utils/constants.ts
  vercel.json
Labels: 🔍 Ready for Review, size/L
